version: '3.8'

services:
  ct-clip-api:
    image: crazyfrogspb/celsus_pli:latest
    build:
      context: ..
      dockerfile: api/Dockerfile
    container_name: ct-clip-inference
    ports:
      - "8000:8000"
    environment:
      - SUPERVISED_MODEL_PATH=/app/best_models/supervised_model.pt
      - CTCLIP_MODEL_PATH=/app/best_models/CT_VocabFine_v2.pt
      - LIGHTGBM_MODEL_PATH=/app/best_models/lightgbm_model.pkl
      - OPTIMAL_THRESHOLD=0.59
      - DEVICE=cuda
      - DIFFUSION_CLASSIFIER_PATH=/app/best_models/ct_classifier.pt
      - DIFFUSION_UNET_PATH=/app/best_models/diffusion_checkpoint.pt
      - CLASSIFIER_SCALE=100.0
      # FVLM модели
      - FVLM_MODEL_PATH=/app/fvlm/weights/fvlm_model.pth
      - FVLM_MAE_WEIGHTS_PATH=/app/fvlm/weights/mae_pretrain_vit_base.pth
      - FVLM_BERT_PATH=/app/fvlm/weights/BiomedVLP-CXR-BERT-specialized
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - /tmp:/tmp
    restart: unless-stopped
