version: '3.8'

services:
  ct-clip-api:
    image: crazyfrogspb/celsus_pli:latest
    build:
      context: ..
      dockerfile: api/Dockerfile
    container_name: ct-clip-inference
    ports:
      - "8000:8000"
    environment:
      - SUPERVISED_MODEL_PATH
      - CTCLIP_MODEL_PATH
      - LIGHTGBM_MODEL_PATH
      - OPTIMAL_THRESHOLD
      - DEVICE
      - DIFFUSION_CLASSIFIER_PATH
      - DIFFUSION_UNET_PATH
      - CLASSIFIER_SCALE
      # FVLM модели
      - FVLM_MODEL_PATH
      - FVLM_MAE_WEIGHTS_PATH
      - FVLM_BERT_PATH
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - /tmp:/tmp
      - ../best_models:/app/models
    restart: unless-stopped
