version: '3.8'

services:
  ct-clip-api:
    image: crazyfrogspb/celsus_pli:latest
    build:
      context: ..
      dockerfile: api/Dockerfile
    container_name: ct-clip-inference
    ports:
      - "8000:8000"
    environment:
      - SUPERVISED_MODEL_PATH=/app/models/supervised_model.pt
      - CTCLIP_MODEL_PATH=/app/models/CT_VocabFine_v2.pt
      - LIGHTGBM_MODEL_PATH=/app/models/lightgbm_model.pkl
      - OPTIMAL_THRESHOLD=0.4
      - DEVICE=cuda
      - DIFFUSION_CLASSIFIER_PATH=/app/models/ct_classifier.pt
      - DIFFUSION_UNET_PATH=/app/models/diffusion_checkpoint.pt
      - CLASSIFIER_SCALE=100.0
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - /tmp:/tmp
      - ../best_models:/app/models
    restart: unless-stopped
